const { EventType } = require('../events');

/**
 * Base class for all action handlers
 * Provides shared validation utilities and consistent error handling
 */
class ActionHandler {
  constructor(gameEngine) {
    this.engine = gameEngine;
    this.state = gameEngine.state;
  }

  /**
   * Abstract method - must be implemented by each handler
   * @param {string} playerId - ID of the player performing the action
   * @param {Object} payload - Action-specific data
   * @returns {Array} Array of events generated by the action
   */
  handle(playerId, payload) {
    throw new Error('handle() must be implemented by subclass');
  }

  // Shared validation utilities

  validateTurn(playerId) {
    if (this.state.currentPlayerIndex === -1) {
      return { error: 'Game not started' };
    }

    const currentPlayer = this.state.players[this.state.currentPlayerIndex];
    if (!currentPlayer || currentPlayer.id !== playerId) {
      return { error: 'Not your turn' };
    }

    return { valid: true, player: currentPlayer };
  }

  validatePlayerOwnsCards(player, cardIndices) {
    if (!player.hand || !player.hand.cards) {
      return { error: 'Player has no cards' };
    }

    for (const idx of cardIndices) {
      if (idx < 0 || idx >= player.hand.cards.length) {
        return { error: `Invalid card index: ${idx}` };
      }
    }
    
    const uniqueIndices = new Set(cardIndices);
    if (uniqueIndices.size !== cardIndices.length) {
      return { error: 'Cannot use the same card twice' };
    }
    
    return { valid: true };
  }

  findCardByUuid(player, cardUuid) {
    if (!player.hand || !player.hand.cards) {
      return { error: 'Player has no cards' };
    }

    if (!cardUuid) {
      return { error: 'No card UUID provided' };
    }

    const cardIndex = player.hand.cards.findIndex(card => card.uuid === cardUuid);
    if (cardIndex === -1) {
      return { error: 'Player does not own that card' };
    }

    return { cardIndex, card: player.hand.cards[cardIndex] };
  }

  // Shared event emission
  emit(type, payload) {
    return this.engine.emit(type, payload);
  }

  // Shared error handling
  createError(message) {
    return [this.emit(EventType.ERROR, { message })];
  }
}

module.exports = ActionHandler;