const EventType = {
  GAME_CREATED: 'GAME_CREATED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  GAME_STARTED: 'GAME_STARTED',
  TURN_STARTED: 'TURN_STARTED',
  CARD_DRAWN: 'CARD_DRAWN',
  CARD_DISCARDED: 'CARD_DISCARDED',
  MELD_LAID: 'MELD_LAID',
  MELD_EXTENDED: 'MELD_EXTENDED',
  DECK_RESHUFFLED: 'DECK_RESHUFFLED',
  PLAYER_QUIT: 'PLAYER_QUIT',
  ROUND_ENDED: 'ROUND_ENDED',
  GAME_ENDED: 'GAME_ENDED',
  ERROR: 'ERROR'
};

module.exports = { EventType };
